name: 'finance_data_platform'
version: '1.0.0'
config-version: 2

profile: 'finance_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_data_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
    metrics:
      +materialized: table

vars:
  # Variables for the project
  finance_data_schema: "finance_data"
  raw_schema: "raw"
  staging_schema: "staging"
  marts_schema: "marts"
  metrics_schema: "metrics"

seeds:
  finance_data_platform:
    +schema: raw
